### ISSUE TITLE
[C4GT Community]:  Convert relative imports to absolute imports

### ISSUE THREAD

**Issue by suryabulusu** [avantifellows/quiz-frontend#154]
## Description
Currently, we are using relative imports in several component files.

About `quiz-frontend`:  A generic player for playing different types of content (questions, etc.) in a mobile-friendly webapp 

## Goals
- [ ] Change to absolute imports. They are easier to understand, remember, and less cumbersome.
- [ ] Ensure that tests don't fail post the changes.

### Expected Outcome

No relative imports exist in repo.

### Implementation Details

Reference : https://justinnoel.dev/2019/06/18/configuring-react-absolute-imports-for-typescript/

### Product Name

Quiz Frontend

### Organisation Name

Avanti Fellows

### Domain

Education

### Tech Skills Needed

Vue.js

### Mentor(s)

@suryabulusu 

### Complexity

Medium

### Category

Frontend

**Comment by harshitkandpal** [comment]
hi I am interested in solving this issue do assign this to me.

**Comment by hardik-pratap-singh** [comment]
Hey @suryabulusu !
I want to work on this issue under Augtoberfest (C4GT)
Please assign this to me..

**Comment by harshitkandpal** [comment]
Thanks for assigning me the task i will be updating you as soon as i setup the backend and frontend

**Comment by harshitkandpal** [comment]
![Screenshot from 2024-08-08 06-43-27](https://github.com/user-attachments/assets/b47b3e0f-4dfc-4aea-8c8d-e11aa9b81579)
![Screenshot from 2024-08-08 06-42-57](https://github.com/user-attachments/assets/8cc5db0b-6e75-4390-a9e3-28a23899ecaf)


hi I have successfully setup the project with front-end and back-end 
Can I have more info on routing and other related stuffs

**Comment by harshitkandpal** [comment]
Hi @suryabulusu  !
 Please check if i am going correct i have using @/ as src/ address and converting all the relative imports ../../ type to @/ type 
 
 so do i need to change only components present in components dir ?

Before
![Screenshot from 2024-08-08 07-26-32](https://github.com/user-attachments/assets/9fd31d8c-142a-41fd-a0e7-1aa3efb263f7)

After
![Screenshot from 2024-08-08 07-30-11](https://github.com/user-attachments/assets/57d11d56-3acb-4a0a-8937-628ee9ca72e2)

**Comment by VedantKhairnar** [comment]
Hello @harshitkandpal 
Pls direct raise the PR, it will be easy to review for @suryabulusu .
Thanks.

**Comment by harshitkandpal** [comment]
@VedantKhairnar sure i will do it till today or tomorrow evening
