### ISSUE TITLE
[C4GT Community]:  Think of instructions page and palette button for omr assessment

### ISSUE THREAD

**Issue by suryabulusu** [avantifellows/quiz-frontend#155]
## Description
- In quiz assessment we can navigate questions through questionPalette and see instructions from the palette itself.
- In omr-assessment there is no need for palette but it is required to show instructions.

## Goals
- [ ] Instruction Page for OMR format
- [ ] Palette for OMR format

### Expected Outcome

Instruction page and palette for OMR format are available on frontend.

### Implementation Details

Read through `OMRModal.vue`, `Player.vue` components.

### Product Name

Quiz Frontend

### Organisation Name

Avanti Fellows

### Domain

Education

### Tech Skills Needed

Vue.js

### Mentor(s)

@suryabulusu 

### Complexity

Medium

### Category

Frontend

**Comment by hardik-pratap-singh** [comment]
I want to work on this issue under Augtoberfest, C4GT.
Please assign this issue to me if possible.

**Comment by hardik-pratap-singh** [comment]
Thanks @suryabulusu for assigning the issue.
I will let you know once I am done with frontend and backend setup on my pc.

**Comment by R4Rohit23** [comment]
Hii @suryabulusu commenting if this issue is still unresolved.

**Comment by hardik-pratap-singh** [comment]
Hi @R4Rohit23 
I have been assigned this issue and I am working on it !!

**Comment by hlukare** [comment]
Hello, I'm Harish Lukare a TYBech CSE student, I want to work on this project's issues can you please assign me this issue under Augtoberfest, C4GT.

**Comment by VedantKhairnar** [comment]
Hello @hardik-pratap-singh 
Any update on the contribution?
Pls do let us know if you need any assistance.
Thanks.

**Comment by VedantKhairnar** [comment]
Hello @hlukare 
Pls directly raise the PR. Just give us an indication that you are working on the issue.
Thanks.

**Comment by sau1606** [comment]
@suryabulusu hey is this issue still unsolved then assign me, i wanna work on this project

**Comment by Vaibhavsahu2810** [comment]
@suryabulusu hey is this issue is still open ,Please assign this issue to me if possible.

**Comment by suryabulusu** [comment]
@sau1606 @Vaibhavsahu2810 Thanks for considering our repo. There's another active PR which is about to be merged for this task. So I'd recommend you to work on other challenging issues. Please check https://github.com/avantifellows/quiz-frontend/issues.

**Comment by Deep5Varshney** [comment]
Hi @suryabulusu,
I hope you're doing well. I came across issue in your repository and would like to contribute by working on it. Please assign the issue to me, and I will ensure all necessary details are implemented effectively.
