### ISSUE TITLE
[C4GT Community]: Multi-language compatibility

### ISSUE THREAD

**Issue by suryabulusu** [avantifellows/quiz-frontend#157]
## Description
 add an option to pick languages.

## Goals
- [ ] Instructions in Hindi
- [ ] Other details in Hindi
- [ ] Ideas to extend to other languages

### Expected Outcome

Frontend displays text in both Hindi and English. 

### Implementation Details

See how Portal Frontend (https://github.com/avantifellows/portal-frontend/) has implemented support for Hindi

### Product Name

Quiz Frontend

### Organisation Name

Avanti Fellows

### Domain

Education

### Tech Skills Needed

Vue.js

### Mentor(s)

@suryabulusu 

### Complexity

High

### Category

Frontend

**Comment by sagarkori143** [comment]
Hi @suryabulusu 
I am interested in working on this issue. Could you please assign this to me?

**Comment by R4Rohit23** [comment]
Hii @suryabulusu 
I have implemented this feature in my project, can you assign this task to me?

**Comment by divineshiva003** [comment]
Hii @suryabulusu 
Please assign this issue to me please 
Want to solve this error in this C4GT Fest

**Comment by sagarkori143** [comment]
Hi @R4Rohit23 and @divineshiva003 I am not getting enough time to work on this issue. Therefore, I am un assigning myself from it and you can ask @suryabulusu to assign it to you. Make sure you explain your approach in the comment section to make it easier for Surya choosing whom the issue should be assigned to.

**Comment by R4Rohit23** [comment]
Hii @suryabulusu I have used Google translate script in my other projects to dynamically translate the whole webpage in any language, so can you assign this issue to me?

**Comment by divineshiva003** [comment]
Hii @suryabulusu I have used Google translate script in my other projects.

Please can you assign this project to me which will help me grow

**Comment by Pranshu-jais** [comment]
Hi @suryabulusu  i have worked on  projects  of translation and displays of  text in both Hindi and English..
Please can you assign this issue to me

**Comment by harshcrop** [comment]
@suryabulusu @divineshiva003 If you think you can solve this, please start working on it immediately—no need to wait for the issue to be assigned to you.

**Comment by VedantKhairnar** [comment]
Hey @R4Rohit23 @divineshiva003 @Pranshu-jais 
Pls directly raise the PR. Do give an indication if you have started working on the same.
Thanks.

**Comment by ananyajain10** [comment]
Working on this issue. 
Thank you.
