### ISSUE TITLE
[C4GT Community]: Reduce text area and increase numerical answer fontsize

### ISSUE THREAD

**Issue by suryabulusu** [avantifellows/quiz-frontend#160]
## Description
Since answers for this question type wont exceed 10 digits typically, we can make the size of text much bigger, while reducing the text area rectangle box size.
However, this may clash with subjective answer text area. Can ignore the task if not necessary.

## Goals
- [ ] reduce text area size
- [ ] increase numerical font size
- [ ] ensure none of this clashes with subjective answer type

### Expected Outcome

See goals

### Implementation Details

see Body.vue and OmrItem.vue

### Mockups/Wireframes

![image](https://github.com/avantifellows/quiz-frontend/assets/21237473/9b7076e9-052b-4d67-900c-7c2fd3a8c9c9)

### Product Name

Quiz Frontend

### Organisation Name

Avanti Fellows

### Domain

Education

### Tech Skills Needed

Vue.js

### Mentor(s)

@suryabulusu 

### Complexity

Low

### Category

Frontend

**Comment by rohra-anisha** [comment]
This issue wants to adjust the relative scaling of the text box area (which needs to be reduced) and increase the font size so it fits in the input box, also this needs to be done only for numerical answers only. I would like to work on this issue. Please assign me this issue to get started.

**Comment by kesharibhai84** [comment]
hey @suryabulusu i want to work on this issue please assign me.

**Comment by Aman1919** [comment]
@suryabulusu If there is no movement . Can i work  on this

**Comment by arghaDEVIL** [comment]
@suryabulusu assign this issue to me please!

**Comment by VedantKhairnar** [comment]
Hello @rohra-anisha ,
Pls let us know if you need any assistance. 
Thanks.

**Comment by VedantKhairnar** [comment]
Hello @Aman1919 @arghaDEVIL 
Pls let us know if you are willing to work on this. If so, we will assign it to you.

@suryabulusu As we haven't heard from Anisha, can we unassign her from the issue?

**Comment by rohra-anisha** [comment]
Hello @VedantKhairnar extremely sorry for not replying. I was having issues with setting up the development, I resolved it with the help of @suryabulusu. I will raise the PR in a day or at max in two.

**Comment by VedantKhairnar** [comment]
Sure thanks for the confirmation Anisha.
