### ISSUE TITLE
Minor: Do not show metadata on Splash if it does not exist in db

### ISSUE THREAD

**Issue by suryabulusu** [avantifellows/quiz-frontend#73]
For example, if `grade`key is not there in quiz retrieved from db, do not show `Class ` in Splash. 

Example of error case:
![image](https://user-images.githubusercontent.com/21237473/176365716-630b345c-fa8d-4f00-89a7-710839efba60.png)

**Comment by Jeevan-Kiran-Lenka** [comment]
Hey @suryabulusu can I work on this issue?
